baseURL = "https://singularisart.github.io"
languageCode = "en-us"
title = "SingularisArt"
disqusShortname = "singularisart-github-io"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.tableOfContents]
    endLevel = 4
    ordered = true
    startLevel = 2

[taxonomies]
  category = "categories"
  tag = "tags"
