baseURL = "https://singularisart.github.io"
languageCode = "en-us"
title = "SingularisArt"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.tableOfContents]
    endLevel = 4
    ordered = true
    startLevel = 2
