baseURL = "https://singularisart.github.io"
languageCode = "en-us"
title = "SingularisArt"
disqusShortname = "singularisart-github-io"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.tableOfContents]
    endLevel = 4
    ordered = true
    startLevel = 2

[taxonomies]
  tag = "tags"
  category = "categories"

[mediaTypes]
  [mediaTypes."text/markdown"]
    suffixes = ["md"]

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  page = ["HTML"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]
