baseURL = "https://singularisart.github.io"
languageCode = "en-us"
title = "SingularisArt"

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = true
    startLevel = 2
